# Site settings
title:       Eating - I mean - Biking NYC
author:      nyc.data.bikers
description: "when data nerds geek out on bikes"
baseurl:     "/captains-log" 
url:         "https://veeps.github.io" 

# Social Links
email:            hi@vivianpeng.com
twitter_username: nyhackr
github_username:  veeps

# Build settings
markdown: kramdown
permalink: pretty
